### ISSUE TITLE
Assess time tracker apps one-by-one (milestone 4)

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#1]
We should go through the [list of time tracker apps](https://github.com/federatedbookkeeping/timesheets/blob/main/apps-list.md) and see & document which ones even have something like an API a CSV export.

So for each of the 250 apps in the list we want to know:
* is it usable as a "tracker"? i.e. for tracking billable hours (some projects may be deprecated)
* is it usable as a "publisher"? i.e. does it have some sort of machine-readable data export (API or CSV export, not html scrape)
* can it import data in some way (API or CSV import, not manual GUI data entry)
* can it handle data from multiple collaborators? (some apps may have an import function but still be designed for just 1 user, so not usable for project aggregate pivot sheets)
*what is the exact data format used for API/import/export, which values can each field take on, and what do these values mean

Who wants to take each of the following chunks:
* [0* - 9*, A* - C*](https://github.com/federatedbookkeeping/timesheets/blame/7fc8bfb/apps-list.md#L5-L46) (roughly 42 apps) -> see #2.
* [D* - H*](https://github.com/federatedbookkeeping/timesheets/blame/7fc8bfb/apps-list.md#L47-L87) (roughly 38 apps) -> see #3.
* [I* - O*](https://github.com/federatedbookkeeping/timesheets/blame/7fc8bfb/apps-list.md#L88-L121) (roughly 33 apps) -> see #4.
* [P* - R*](https://github.com/federatedbookkeeping/timesheets/blame/7fc8bfb/apps-list.md#L122-L149) (roughly 28 apps) -> see #5.
* [S* - Timd*](https://github.com/federatedbookkeeping/timesheets/blame/b017c0c/apps-list.md#L150-L180) (roughly 31 apps) -> see #6.
* [Time*](https://github.com/federatedbookkeeping/timesheets/blame/b017c0c/apps-list.md#L181-L228) (roughly 46 apps) -> see #7.
* [Timf* - Z*](https://github.com/federatedbookkeeping/timesheets/blame/b017c0c/apps-list.md#L229-L268) (roughly 40 apps) -> see #8.

**Comment by michielbdejong** [comment]
The milestone says we'll put it in a wiki but for now we're doing it in [apps-list.md](https://github.com/federatedbookkeeping/timesheets/blob/main/apps-list.md) with links to the actual formats in [the data-formats folder](https://github.com/federatedbookkeeping/timesheets/tree/main/data-formats).

We'll also have to create the shortlist to be used for milestones 1,2, and 3 at some point.

**Comment by michielbdejong** [comment]
Wrapping this up in #43

**Comment by Angus-McAllister** [comment]
> The milestone says we'll put it in a wiki but for now we're doing it in [apps-list.md](https://github.com/federatedbookkeeping/timesheets/blob/main/apps-list.md) with links to the actual formats in [the data-formats folder](https://github.com/federatedbookkeeping/timesheets/tree/main/data-formats).

Could I suggest mentioning this in the Wiki as originally envisaged, with links to the above two documents?  That way, the Wiki is the starting point for anyone evaluating the project, and the guide to the supporting resources demonstrating that its commitments have been fulfilled.
