### ISSUE TITLE
Import from various formats into WikiSuite (milestone 3a)

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#30]
See https://github.com/federatedbookkeeping/timesheets#milestone-3-wikisuite

**Comment by kroky** [comment]
Import from timeld.org gateway works on timesheet.dev3.evoludata.com via tabular 11: https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=11

**Comment by Angus-McAllister** [comment]
Great news!

**Comment by kroky** [comment]
In fact, this is done on purpose. We don't track timesheet records internally in Tiki, so I have to artificially create them. We discussed with @gsvarovsky that I can use user/project as the timesheet identifier and that's what I do. The integration currently uses fedb/fedt as the project and refers to different Tiki projects as timesheets. Do you see an issue using this approach? Not sure why the data is not visible in timeld but it is definitely accepted via the timeld API.

**Comment by kroky** [comment]
Milestone 3a has been completed. Demonstration could be done via 2 ways:
1. Install Tiki (https://tiki.org/Get-Tiki), Install Timesheets profile (https://profiles.tiki.org/Timesheets), configure DSN/Content authentication with your credentials for pondersource and timeld. Configure tabular formats for Mite, Scoro and Time with proper API endpoints depending on your accounts in these 3rd parties. Add local Tiki users for all the users you plan to import data for.
2. This is what has been done in https://timesheet.dev3.evoludata.com - you can register and use the existing tabular formats there.

Usage:
1. manual import using Import button in existing tabulars in the following formats:
  1.1. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=6 - Full format using the WikiSuite/Tiki timesheet format.
  1.2. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=7 - csv format for Time app
  1.3. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=8 - json format using the Scoro API
  1.4. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=9 - json format using the Mite API
  1.5. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=10 - json format using the Pondersource/Prejournal API
  1.6. https://timesheet.dev3.evoludata.com/tiki-tabular-list?tabularId=11 - ndjson format using the timeld API
2. automated import using Tiki Scheduler - a job could be scheduled to run on a specific interval and does the import in an automated way. 1.5. and 1.6. import require parameters (worker/user and project), so distinct import jobs need to be configured for distinct users/projects.
