### ISSUE TITLE
Accessing the API of https://time.pondersource.com

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#41]
We have a Prejournal instance running on  https://time.pondersource.com to keep track of the timesheet data of Ponder Source team members. It also tracks hours from other teams (m-ld, Muze, EvoluData, etc) if that other team has opened that data up to us.

I created an example account 'example' which we can use for debugging, as follows:
```
curl -d'["nlnet-timesh:Federated Timesheets","0","100"]' https://example:password123@time.pondersource.com/v1/print-timesheet-json
[
    {
        "id": 1,
        "worker": "ismoil",
        "project": "nlnet-timesh:Federated Timesheets",
        "timestamp_": "2022-09-12 00:00:00",
        "amount": "40",
        "description": ""
    }
]
```
There's only one entry there so far but we're in the process of loading our real live data onto it. Just need to set up some access control before we do that. ;)

I'll also create users for the other two Tier-2 nodes in the network (https://timeld.org/ and  https://timesheet.dev3.evoludata.com/).

**Comment by kroky** [comment]
@ishifoev @michielbdejong are we still planning on using unique URI for the entries generated on the source system or we phased out this idea?

**Comment by kroky** [comment]
I was under the impression that each source system will assign/generate a unique URI (might be UUID, might be just any type of URI, for example wikisuite might use an actual url to the item from the API, like https://timesheet.dev3.evoludata.com/api/trackers/1/items/1) that will be shared with other "Tier 1" systems. This way, other systems won't have to store N+1 source IDs and will also have a reference to the remote item if needed + ability to determine the source system. If we move away from this idea to the source_id idea then I will have to extend wikisuite to handle it. Not sure if you discussed this more in the recent meetings?

**Comment by michielbdejong** [comment]
Yes sorry, see https://gitter.im/federatedbookkeeping/timesheets?at=62dfe4f30a52264798942401
The response is plain text as you can see, we should probably change that to a JSON response, I created https://github.com/pondersource/prejournal/issues/115 about that. @ishifoev what do you think about it?

**Comment by kroky** [comment]
Besides the JSON response, is there also a way to update an entry that has already been created?
Also, can you show the description of the timesheet entry in the print-timesheet-json endpoint?

**Comment by ishifoev** [comment]
@kroky   
``` curl -d'["update-entry", "23 August 2021",   "ismoil:test",      2,      worked,    2]' https://example:password123@time.pondersource.com/v1/update-entry
```

**Comment by ishifoev** [comment]
@kroky I will add description, we have description in our system we just move it in another table.

**Comment by Angus-McAllister** [comment]
@michielbdejong and @ishifoev, I've updated the [API Definitions Wiki page](https://github.com/federatedbookkeeping/timesheets/wiki/API-Definitions-for-Federated-Time-tracking-tools) with an edited reproduction of the content of this thread relating to PreJournal, including a description of the expected data format.  As a first draft, it's likely to have inaccuracies, so could you review and correct / augment as necessary?  Thanks!

**Comment by michielbdejong** [comment]
Thanks! I think the part about time.pondersource.com looks accurate so far. @ishifoev can you add documentation for the `worked-hours` command so EvoluData and M-LD can also push data to it?

**Comment by michielbdejong** [comment]
Hi @kroky sorry I missed your questions earlier, you wrote:
> Besides the JSON response, is there also a way to update an entry that has already been created?

Sorry, we hadn't answered that question yet. Yes, see https://github.com/pondersource/prejournal#usage-timepondersourcecom

> Also, can you show the description of the timesheet entry in the print-timesheet-json endpoint?

It's already included, I think?

**Comment by ishifoev** [comment]
@michielbdejong We have a doc for worked-hours or you would like need to separete API documentation?

**Comment by ishifoev** [comment]
@michielbdejong  not is not included, because we have it in movement table first, for now it is in statement. I just create PR for it.

**Comment by kroky** [comment]
@ishifoev can you also add the description in the update-entry command? One should be able to edit the description, right?
Also, I noticed that the docs says timestamp, project, amount with the second field being the project but the actual code uses second and third params of the command to concatenate as user:project. What is the correct format to update an entry? Is the type parameter here always equal to 'worked'?

**Comment by ishifoev** [comment]
@kroky I just update you can only project without use username. The worked not need because we used it when import ours, Only if you know id it will be enough to update. About description for now, it is for edit, I think not paste. But I will think about it for update entry.

**Comment by ishifoev** [comment]
@kroky I think I can add description too for your update, I created PR for it. Will be ready, soon.

**Comment by michielbdejong** [comment]
That was done, see https://github.com/pondersource/prejournal/blob/a17963076eb3082975b659c52db5e110255bd5a7/tests/ImportTimesheetTest.php#L1027
