### ISSUE TITLE
Using timesheet-dev3-evoludata-com

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#45]
I'm trying out timesheet-dev3-evoludata-com and ran into some questions. Shall I list them here or is there an issue tracker elsewhere you prefer to use?

#### First issue: how to manually add an entry
-> see #46

**Comment by kroky** [comment]
Yes, please list them here. Answered the first one in #46

**Comment by michielbdejong** [comment]
I can now log in as `michielbdejong` and see Victor's hours in the GUI in http://timesheet.dev3.evoludata.com/tracker2 \o/
Will find the API docs and see if I can fetch them with curl.

**Comment by michielbdejong** [comment]
```
curl -X 'GET' \
  'https://timesheet.dev3.evoludata.com/api/tabulars' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer dbcafe758b...'

{
  "title": "Tabular Formats",
  "list": [
    {
      "tabularId": "6",
      "name": "Timesheet - Full",
      "trackerId": "2"
    },
    {
      "tabularId": "7",
      "name": "Timesheet - Time",
      "trackerId": "2"
    },
    {
      "tabularId": "8",
      "name": "Timesheet - Scoro",
      "trackerId": "2"
    },
    {
      "tabularId": "9",
      "name": "Timesheet - Mite",
      "trackerId": "2"
    },
    {
      "tabularId": "10",
      "name": "Timesheet - pondersource",
      "trackerId": "2"
    },
    {
      "tabularId": "11",
      "name": "Timesheet - timeld",
      "trackerId": "2"
    }
  ]
}
```

So the tabulars seem to be export formats, all of them are for Tracker2 which is the one we want so that's good. I'll try 'full'

**Comment by michielbdejong** [comment]
```
curl -X 'GET' \
  'https://timesheet.dev3.evoludata.com/api/tabulars/6/export' \
  -H 'accept: */*' \
  -H 'Authorization: Bearer dbcafe758b...'

works! \o/

**Comment by michielbdejong** [comment]
I received it from Ismoil via Slack message :)

**Comment by kroky** [comment]
OAuth server is not setup, I think. I can issue an access token for your user once you register. It is a manual operation for the moment.

**Comment by Angus-McAllister** [comment]
Thanks both!  I've just seen on the relevant [Federated Timesheets Wiki page](https://github.com/federatedbookkeeping/timesheets/wiki/API-Definitions-for-Federated-Time-tracking-tools) that they can be obtained from Evoludata - now that I've registered, I'll request one from you by DM, @kroky.
