### ISSUE TITLE
[timesheet-dev3-evoludata-com] no GUI feedback when manually creating an entry

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#46]
I was able to register `michielbdejong` on https://timesheet.dev3.evoludata.com/ and tried the top link "[Timesheets entry - date and duration](https://timesheet.dev3.evoludata.com/Timesheets%20entry%20-%20date%20and%20duration)". I was able to fill in a form for but duration was `0h00` and I could not edit it. After I clicked 'Save' I saw this screen: 
<img width="850" alt="Screenshot 2022-08-10 at 08 03 39" src="https://user-images.githubusercontent.com/408412/183827096-4fc17c94-dcdb-41dd-972a-f18b601a35cd.png">

It seems the entry was added successfully to https://timesheet.dev3.evoludata.com/tracker1

So what was missing is a message  saying "Saved to [tracker1](https://timesheet.dev3.evoludata.com/tracker1)", maybe?

**Comment by kroky** [comment]
Thanks for the report. Added the success msg when creating an entry.

If you click on the duration (0h 0m) it should open a modal to enter your time duration. Something like this:
![Screenshot from 2022-08-10 17-23-10](https://user-images.githubusercontent.com/2064350/183926757-cbfbb4c7-e104-4c8c-ac54-b19383b54884.png)
