### ISSUE TITLE
Using Timeld

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#47]
@Angus-McAllister has now entered his timesheet data into Timeld and I'm trying to to use https://github.com/m-ld/timeld/blob/main/doc/api.md#report to read it.

What should be the API call? Something like `curl https://timeld.org/api/rpt/michielbdejong/own/angus`?
Or do I need Angus's password to read Angus's timesheet entries?

If the latter, maybe we should just use a single 'team' account on https://timeld.org where we all have access?

**Comment by gsvarovsky** [comment]
We have now added an organisation `fedb`, with:
- admins `angus`, `george`, `ismoil`, `michielbdejong` and `victor`
- a project `fedt`

Angus has added his timesheet `ts-agm-2022-08-08` to the project. So now, anyone in the `fedb` team can report on it!

To report only on Angus's timesheet:
```
curl https://timeld.org/api/rpt/angus/own/ts-agm-2022-08-08 -u michielbdejong:***
```

To report on the whole project:
```
curl https://timeld.org/api/rpt/fedb/own/fedt  -u michielbdejong:***
```

**Comment by michielbdejong** [comment]
Great! Trying to remember my password now :)

**Comment by michielbdejong** [comment]
Ah, found it :)
```sh
$ vim /Users/michiel/.nvm/versions/node/v16.16.0/lib/node_modules/timeld-cli/node_modules/timeld-common/lib/Env.mjs # added console.log statement on line 75
$ timeld list
reading config file from /Users/michiel/Library/Preferences/timeld-nodejs/config.json
$ grep key /Users/michiel/Library/Preferences/timeld-nodejs/config.json
[... prints my password ...]
```

**Comment by michielbdejong** [comment]
Awesome, thanks a lot for making this quick progress!
