### ISSUE TITLE
[timesheet-dev3-evoludata-com] How to get JSON instead of out of WikiSuite

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#48]
When I run:
```sh
curl -X 'GET' 'https://timesheet.dev3.evoludata.com/api/tabulars/6/export' -H 'accept: */*' -H 'Authorization: Bearer dbcafe758b6...'
```
I get CSV.

I tried:
```sh
curl -X 'GET' 'https://timesheet.dev3.evoludata.com/api/tabulars/6/export' -H 'Accept: application/json' -H 'Authorization: Bearer dbcafe758b6...'
```
but I still get CSV? Which Accept header should I send to get JSON?

**Comment by kroky** [comment]
Tabular data format is currently set to CSV. You can change it to JSON here: https://timesheet.dev3.evoludata.com/tiki-tabular-edit?tabularId=6 but I am not sure if someone else is using it. Maybe make a copy of that Full tabular format just for your usage and change that?

**Comment by michielbdejong** [comment]
OK I'll just import the CSV then, no problem!
