### ISSUE TITLE
Interpreting top 2 lines of a m-ld.ndjson

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#49]
The top two lines of the `m-ld.ndjson` file which I now obtained through https://github.com/federatedbookkeeping/timesheets/issues/47 read:

```
{"@id":"fedb/fedt","@type":"Project"}
{"@id":"angus/ts-agm-2022-08-08","project":{"@id":"fedb/fedt"},"@type":"Timesheet"}
```

Does this imply that all subsequent lines pertain to that project and that timesheet?

**Comment by michielbdejong** [comment]
Sorry this issue should have gone to https://github.com/m-ld/timeld but I guess we can also answer it here as part of https://github.com/federatedbookkeeping/timesheets/wiki/Timesheet-Data-Formats

**Comment by gsvarovsky** [comment]
> Does this imply that all subsequent lines pertain to that project and that timesheet?

Yes, see https://github.com/m-ld/timeld/blob/main/doc/api.md#report

Note also https://github.com/m-ld/timeld/issues/44: The `session` key in each Entry leaks an internal identifier instead of the timesheet reference.
