### ISSUE TITLE
Clarify timeld-tiki integration

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#55]
At https://youtu.be/79bTn8JDtIk?t=1052 you add a connector:
```sh
timeld admin
george> add connector timeld-tiki --ts fedt-1
```

I assume this is a predefined connector that timeld-org knows about and that contains details about timesheet-dev3-evoludata-com. Question 1: Where is this configuration and how would one go about setting this up in a different network, for instance a testnet as we'll probably want to do for #32?

**Comment by michielbdejong** [comment]
Question 2: At https://youtu.be/79bTn8JDtIk?t=1165 you say "Let's synchronise over here" and click "Sync" on the Tiki Tracker page. Could you also have just refreshed the page, or does that Sync button cause the data to be fetched?

**Comment by michielbdejong** [comment]
Ah, found the answer to question 1 here: https://github.com/m-ld/timeld/tree/main/packages/tiki#installation--configuration

**Comment by gsvarovsky** [comment]
> Could you also have just refreshed the page, or does that Sync button cause the data to be fetched?

Sync is a pre-existing Tiki button that refreshes the displayed list on the page (as far as I know... @kroky?). I could also have just refreshed the page, because the timesheet entry has already been pushed into Tiki from timeld. Shame this was not clear enough!

**Comment by kroky** [comment]
I am not sure it is a Tiki button - haven't really noticed it until now and certainly don't remember coding it - might it be a browser button that refreshes the page or a plugin of some kind? I think it just do a page refresh.

**Comment by michielbdejong** [comment]
Great, thanks for clarifying!
