### ISSUE TITLE
How to configure Tiki - Scoro integration

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#56]
I tried to import data from Scoro but saw this error:

<img width="806" alt="Screenshot 2022-09-20 at 09 53 27" src="https://user-images.githubusercontent.com/408412/191200114-866c2b60-45df-4e30-8dc2-511b81dad78c.png">

It seems that 'company' is a placeholder string there, where can I configure it?

**Comment by kroky** [comment]
Tabular format needs configuration here: https://timesheet.dev3.evoludata.com/tiki-tabular-edit?tabularId=8

I also made your user an admin as I think you will need to supply your API credentials here: https://timesheet.dev3.evoludata.com/tiki-admin_dsn.php - just add a content authentication section for scoro with correct user/pass or whatever API credentials that required.

**Comment by michielbdejong** [comment]
Thanks!
