### ISSUE TITLE
Investigate time tracker apps Time*

### ISSUE THREAD

**Issue by michielbdejong** [federatedbookkeeping/timesheets#7]
[Time*](https://github.com/federatedbookkeeping/timesheets/blame/b017c0c/apps-list.md#L181-L228) (roughly 46 apps)

**Comment by ishifoev** [comment]
The first app time https://github.com/wbbly/time have export CSV file and working with https://github.com/wbbly/time-api. React JS send to Node JS API fetching data and use export CSV client talk with server and format look like
[report_2022-03-18 09 40 47.csv](https://github.com/federatedbookkeeping/timesheets/files/8301691/report_2022-03-18.09.40.47.csv)

**Comment by ishifoev** [comment]
182 Time and Labor, the second app I think it is not free I send request, that we can use or not they not send me anything will wait.

**Comment by ishifoev** [comment]
183 Time Bro. This is app working for windows or mac app. It is free for month and yes it is working for export report for CSV, Excel and PDF. I think they take from API, but it can use for month after it you need to buy subscription.
[2022Y0318_102736_Time_Report.csv](https://github.com/federatedbookkeeping/timesheets/files/8301850/2022Y0318_102736_Time_Report.csv)
https://www.timebro.com/)

**Comment by ishifoev** [comment]
184 Timecamp. This app have the same thing 14 days trial. Yes have export function for CSV and have integration with FreshDesk have own API I don't figure out how to connect both one. But Timechamp can export without freshDesk.
[projectsAndTasks.csv](https://github.com/federatedbookkeeping/timesheets/files/8302016/projectsAndTasks.csv)

https://www.freshworks.com/apps/freshdesk/timecamp_time_tracking/

**Comment by ishifoev** [comment]
185 Timecop https://github.com/hamaluik/timecop have a feature Export data as a .csv file, filtered by timespans and projects. But I can't see it because it is payable application $0.78.
 
https://play.google.com/store/apps/details?id=ca.hamaluik.timecop

**Comment by ishifoev** [comment]
186 Timed https://github.com/adeel/timed very good app for working with CLI use Python, but very old. It is not working with Python3 and have a problem with installation.

**Comment by ishifoev** [comment]
187Time Doctor’s time tracking software will show you both high level and granular data about how much time you and your employees spend on every Freshdesk ticket. 
https://www.freshworks.com/apps/freshdesk/time_doctor
[Custom-export_2022-03-18_in-each-users-timezone.csv](https://github.com/federatedbookkeeping/timesheets/files/8303324/Custom-export_2022-03-18_in-each-users-timezone.csv)

**Comment by ishifoev** [comment]
188 Timeero working with it install application in phone it is not have export function.
https://play.google.com/store/apps/details?id=com.timeero.time_clock

**Comment by ishifoev** [comment]
189 Time glass http://timeglassapp.io/ This is app for apple and for android. But they don't have this functionality.

**Comment by ishifoev** [comment]
190 Timelog They don't have a export function..

https://play.google.com/store/apps/details?id=dev.giall.timelog

**Comment by ishifoev** [comment]
191 Timely have export CSV and other function very good but mostly GUI.

https://www.freshworks.com/apps/freshdesk/timely/

**Comment by ishifoev** [comment]
192 **Time manager** it is nextcloud plugin have export for reports, I don't use myself but see in new version they say add this functionality.
 https://github.com/te-online/timemanager

**Comment by ishifoev** [comment]
193 **Timemeter**  I worked with this app, if you need use export function and statistics work you need pay 5 dollar.
(https://play.google.com/store/apps/details?id=com.rk.timemeter)
http://timemeter.io/

**Comment by ishifoev** [comment]
194 **TimePouch** very good cli time tracker, but it 10 years ago, not update and have a problem with dependencies. If you install it you have a problem with old a new version Node.
https://github.com/chesles/timepouch

**Comment by ishifoev** [comment]
195 **TimePulse** this app the last update is 5-10 years ago and I think it out of date not working with Rubu last version and have a problem with installation.

https://github.com/TimePulse/TimePulse

**Comment by ishifoev** [comment]
196 **Time Recorder** They have export excel and html, you can see it when install in mobile.

https://play.google.com/store/apps/details?id=com.dynamicg.timerecording

**Comment by ishifoev** [comment]
197 **Timesheet** They have both web and mobile, and export function CSV.

https://timesheet.website
https://play.google.com/store/apps/details?id=robin.urenapp

**Comment by ishifoev** [comment]
198 **Timesheet** They have one problem this app can do a report only if you are pay 5 dollar.
https://play.google.com/store/apps/details?id=com.unidevsolutions.timesheet

**Comment by ishifoev** [comment]
199 TimeSheet History good app,export to excel but have a problem need to pay 2 dollar for it. The most that don't have a public repostiories it is a private only mobile.

https://play.google.com/store/apps/details?id=com.forutan.app.timesheethistory

**Comment by ishifoev** [comment]
199 TimeSheet History good app,export to excel but have a problem need to pay 2 dollar for it. The most that don't have a public repostiories it is a private only mobile.
https://play.google.com/store/apps/details?id=com.forutan.app.timesheethistory

**Comment by ishifoev** [comment]
200 **Timesheet** Mobile working with CSV file and work web and mobile platform very good for using.

https://timesheetmobile.com

**Comment by ishifoev** [comment]
202 **TimeSheet Tracker** You can signup and check it in web how to export excel file and send it to recipient for example. Mobile app working too.

https://timesheet.io/
https://play.google.com/store/apps/details?id=com.rauscha.apps.timesheet

**Comment by ishifoev** [comment]
203 **Timesheet - Time Card** Have a export csv, excel like write in description app 

https://play.google.com/store/apps/details?id=com.aadhk.time

**Comment by ishifoev** [comment]
204 Timesheet Track Hours Salary Have export excel mobile and working only for 30 days after it need go to pro.
https://play.google.com/store/apps/details?id=com.bakua.worktimemanager

**Comment by ishifoev** [comment]
205 **Timesheet track hours** it is manually add only hours, but not do anything 

https://play.google.com/store/apps/details?id=com.sullivansoftware.timesheetapp

**Comment by ishifoev** [comment]
206 **Timesheets** have a problem with installation break. 6 years ago out of the date.

https://github.com/hardchor/timesheets

**Comment by ishifoev** [comment]
207 **Timesheets** have a problem with sign in with phone google2fa not working.

https://play.google.com/store/apps/details?id=com.singlebyte.harvest

**Comment by ishifoev** [comment]
209 **TimesTrap** Time tracking you can host anywhere. Full export support in multiple formats and easily extensible. Honestly I didn't check properly install with docke or can deploy to heroku.

https://github.com/overshard/timestrap

**Comment by ishifoev** [comment]
210 **TimeTell** They have export excel and pdf I read in description, but before you need to send request to company. I don't know why they don't give you access directly.
https://timetell.com/software-modules/

**Comment by ishifoev** [comment]
211 **TimeTrip**  Very interesting CLI tool for time tracking and have export in json 
```
{
  "dates": [
    {
      "date": "2022-03-27T19:00:00.000Z",
      "entries": [],
      "last": {
        "type": "break",
        "reason": "coffee break",
        "date": "2022-03-28T04:59:00.000Z",
        "duration": 104580
      },
      "summary": {
        "productive": 0,
        "total": 0,
        "start": null,
        "finish": null
      },
      "today": true
    }
  ]
}

```

**Comment by ishifoev** [comment]
212 **Time Track** Need a phone a number and password don't have a sign up need to send request for get information by email. I think they don't have export function.

https://trackingtime.org
https://play.google.com/store/apps/details?id=com.time_tracking.user006test.timetracking

**Comment by ishifoev** [comment]
213 **TimeTrack** for Macos have only start time, pause and reset time and only using for MacOS users.

https://github.com/torsten/TimeTrack

**Comment by ishifoev** [comment]
214 **TimeTracker** Out of the date the document that use the domain not working. But I think they don't have anything may be we need, good doc for working. I don't touch yet.

https://github.com/knewter/time-tracker

**Comment by ishifoev** [comment]
215 **TimeTracker* Have export function and working with hours billing csv, excel pdf
[report_2022-03-01_2022-03-31.csv](https://github.com/federatedbookkeeping/timesheets/files/8359845/report_2022-03-01_2022-03-31.csv)
*
https://github.com/anuko/timetracker

**Comment by ishifoev** [comment]
216 Time Tracker it is a tracker app for mobile and web have 14 days trial after it you need to pay have export csv, excel and pdf.
[Time Tracker Weekly Schedule_03272022.csv](https://github.com/federatedbookkeeping/timesheets/files/8359978/Time.Tracker.Weekly.Schedule_03272022.csv)


https://play.google.com/store/apps/details?id=com.cg.android.ebillitytimetracker
https://www.ebillity.com/pricing/?_aiid=13992

**Comment by ishifoev** [comment]
217 **TimeTracker** CLI python project baiesdev for tracking time have export CSV I have some error and not touch good.

https://github.com/eyscode/timetracker

**Comment by ishifoev** [comment]
218 **TimeTracker** I think they have data export I see in issues the people create export CSV. But I don't touch myself.

https://github.com/mtierltd/timetracker
https://apps.nextcloud.com/apps/timetracker

**Comment by ishifoev** [comment]
219 **TimeTracker**  Good application, but have a problem with export you need to pay $6 for it.

https://play.google.com/store/apps/details?id=zzz1zzz.tracktime

**Comment by ishifoev** [comment]
220 **Time Tracker - Timesheet** report have a timesheet for export CSV.
```csv
Date range: 01.03.2022 - 31.03.2022

Test-Domain: 80h 00m

Total: 80h 00m
```
https://play.google.com/store/apps/details?id=ch.gridvision.pbtm.androidtimerecorder

**Comment by ishifoev** [comment]
221 **Time Tracker CLI** have export for JSON and can show by CLI what you need very great tool.
```csv
Name          │ Description │   Dates    │ Duration    ║
╟───────────────┼─────────────┼────────────┼─────────────╢
║ ismoil        │      -      │   28/03    │ 00h 00m 13s
```

https://github.com/danibram/time-tracker-cli

**Comment by ishifoev** [comment]
222 **Time Tracker Mac** Export csv have this open source, but I don't touch it. I think it is for Mac and I can do it later.

https://github.com/rburgst/time-tracker-mac

**Comment by ishifoev** [comment]
223 **TimeTracker Mac** I think it the same that 222, but it is another repository for mac working with google

https://github.com/avh4/time-tracker-for-mac

**Comment by ishifoev** [comment]
225 **TimeTrackrs** Have a good dashboard, I don't touch yet, but I think they don't have export function.
 
https://github.com/phiresky/timetrackrs

**Comment by ishifoev** [comment]
227 **Time Tracker Flutter Course** it is paid course from Udemy somebody deploy it to gihtub, but I see oveview they don't have function export.

https://github.com/bizz84/time_tracker_flutter_course

**Comment by ishifoev** [comment]
228 **Timewarrior**  have export json file and it is working very good cli time tracker.
```json
[
{"start":"20220328T090953Z","tags":["Read chapter 12"]}
]
```
https://timewarrior.net/docs/

**Comment by michielbdejong** [comment]
Hi @ishifoev , please edit the various columns in https://github.com/federatedbookkeeping/timesheets/blob/main/apps-list.md and add the import/export formats you find in https://github.com/federatedbookkeeping/timesheets/tree/main/data-formats. Let me know in https://gitter.im/federatedbookkeeping/timesheets if you run into any questions!

**Comment by ishifoev** [comment]
@michielbdejong Yes finished the exploring 47 application and tomorrow I will start add to list. Step by step will go.

**Comment by michielbdejong** [comment]
Great, thanks a lot! See #43 for the wrap up of milestone 4.
